image: "nisectuni/qubip-ossl-rust-runner:latest-nix"
variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  before_script:
    - export DEBIAN_FRONTEND=noninteractive

    # Spit out relevant info
    - rustc --version
    - cargo --version
    - openssl version -a

stages:
  - lint
  - test

just-list:
  stage: test
  script:
    - cargo build
    - export RUST_LOG=info
    - openssl list -verbose -providers -provider $PWD/target/debug/libaurora.so
    - openssl list -verbose -all-algorithms -provider $PWD/target/debug/libaurora.so

test-code:
  stage: test
  script:
    - cargo build
    - export RUST_LOG=info
    - cargo test --no-fail-fast
    #- cargo install cargo-tarpaulin
    #- cargo tarpaulin --ignore-tests

test-code-pqclean:
  stage: test
  script:
    #- CARGO_INSTALL_ROOT=/ cargo install cargo-nextest --version 0.9.100 --locked
    - CARGO_INSTALL_ROOT=/ cargo install jaq
    - QUERY='.features.default - ["default_adapters"] + .features.default_adapters - ["mldsa_native_adapter"] + ["pqclean_adapter"] | join(",")'
    - TEST_FEATURES="$(jaq -r "$QUERY" Cargo.toml)"
    - echo "TEST_FEATURES=\"${TEST_FEATURES}\"" >&2
    - cargo build --no-default-features --features="${TEST_FEATURES}"
    - export RUST_LOG=info
    - OPENSSL_MODULES="$PWD/target/debug" openssl list -verbose -providers -provider libaurora
    - cargo test --no-fail-fast --no-default-features --features="${TEST_FEATURES}"

test-code-release-native-built_info:
  stage: test
  script:
    - TEST_FEATURES="native,built_info"
    - echo "TEST_FEATURES=\"${TEST_FEATURES}\"" >&2
    - cargo build --release --features "${TEST_FEATURES}"
    - export RUST_LOG=info
    - OPENSSL_MODULES="$PWD/target/release" openssl list -verbose -providers -provider libaurora
    - cargo test --release --features "${TEST_FEATURES}" --no-fail-fast

test-doc:
  stage: test
  script:
    - cargo doc --document-private-items

lint-code:
  stage: lint
  script:
    #- rustup component add rustfmt
    - cargo fmt -- --check
    #- rustup component add clippy
    #- cargo clippy -- -D warnings
# audit-code:
#   stage: test
#   script:
#     - cargo install cargo-audit
#     - cargo audit
